using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
namespace VoidNone.DependencyInjection.Generator;

[Generator]
public sealed class ServiceCollectionExtensionsGenerator : ISourceGenerator
{
    private static readonly DiagnosticDescriptor InvalidServiceType = new(
        id: "VNDI001",
        title: "Invalid service registration",
        messageFormat: "Type '{0}' cannot be registered as service '{1}'.",
        category: "VoidNone.DependencyInjection",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly SymbolDisplayFormat FullyQualifiedTypeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.None);

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (string.Equals(context.Compilation.AssemblyName, "VoidNone.DependencyInjection", StringComparison.Ordinal))
        {
            return;
        }

        var lifetimeAttribute = context.Compilation.GetTypeByMetadataName("Microsoft.Extensions.DependencyInjection.LifetimeAttribute");
        if (lifetimeAttribute is null)
        {
            return;
        }

        var registrations = new List<Registration>();

        foreach (var implementationType in GetAttributedTypes(context.Compilation.GlobalNamespace, lifetimeAttribute))
        {
            if (implementationType.TypeKind != TypeKind.Class || implementationType.IsAbstract)
            {
                continue;
            }

            var grouped = new Dictionary<RegistrationKey, RegistrationBuilder>(RegistrationKeyComparer.Instance);

            foreach (var attribute in implementationType.GetAttributes())
            {
                if (attribute.AttributeClass is null || !InheritsFrom(attribute.AttributeClass, lifetimeAttribute))
                {
                    continue;
                }

                if (!TryReadLifetime(attribute, out var lifetime, out var keyExpression, out var serviceTypes))
                {
                    continue;
                }

                var registrationKey = new RegistrationKey(lifetime, keyExpression);
                if (!grouped.TryGetValue(registrationKey, out var builder))
                {
                    builder = new RegistrationBuilder(lifetime, keyExpression);
                    grouped.Add(registrationKey, builder);
                }

                foreach (var serviceType in serviceTypes)
                {
                    if (!CanRegisterAsService(implementationType, serviceType))
                    {
                        var location = attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation();
                        context.ReportDiagnostic(Diagnostic.Create(InvalidServiceType, location, implementationType.ToDisplayString(FullyQualifiedTypeFormat), serviceType.ToDisplayString(FullyQualifiedTypeFormat)));
                        continue;
                    }

                    builder.AddServiceType(serviceType);
                }
            }

            foreach (var builder in grouped.Values)
            {
                registrations.Add(builder.Build(implementationType));
            }
        }

        context.AddSource("ServiceCollectionExtensions.g.cs", GenerateSource(registrations));
    }

    private static string GenerateSource(List<Registration> registrations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine();
        builder.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine("public static class ServiceCollectionExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    public static IServiceCollection AddFromAttributes(this IServiceCollection services)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(services);");
        if (registrations.Count > 0)
        {
            builder.AppendLine("        RegisterGeneratedServices(services);");
        }

        builder.AppendLine("        if (!services.Any(descriptor => descriptor.ServiceType == typeof(IServiceCollection)))");
        builder.AppendLine("        {");
        builder.AppendLine("            services.AddSingleton(services);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return services;");
        builder.AppendLine("    }");
        builder.AppendLine();

        if (registrations.Count > 0)
        {
            builder.AppendLine("    private static void RegisterGeneratedServices(IServiceCollection services)");
            builder.AppendLine("    {");

            foreach (var registration in registrations)
            {
                AppendRegistration(builder, registration);
            }

            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static IEnumerable<INamedTypeSymbol> GetAttributedTypes(INamespaceSymbol namespaceSymbol, INamedTypeSymbol lifetimeAttribute)
    {
        foreach (var nestedNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            foreach (var type in GetAttributedTypes(nestedNamespace, lifetimeAttribute))
            {
                yield return type;
            }
        }

        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            foreach (var candidate in GetAttributedTypes(type, lifetimeAttribute))
            {
                yield return candidate;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetAttributedTypes(INamedTypeSymbol typeSymbol, INamedTypeSymbol lifetimeAttribute)
    {
        if (typeSymbol.GetAttributes().Any(attribute => attribute.AttributeClass is not null && InheritsFrom(attribute.AttributeClass, lifetimeAttribute)))
        {
            yield return typeSymbol;
        }

        foreach (var nestedType in typeSymbol.GetTypeMembers())
        {
            foreach (var candidate in GetAttributedTypes(nestedType, lifetimeAttribute))
            {
                yield return candidate;
            }
        }
    }

    private static void AppendRegistration(StringBuilder builder, Registration registration)
    {
        var implementationType = FormatTypeExpression(registration.ImplementationType);

        if (registration.ServiceTypes.Length == 0)
        {
            AppendDescriptor(builder, implementationType, implementationType, registration.Lifetime, registration.KeyExpression);
            return;
        }

        foreach (var serviceType in registration.ServiceTypes)
        {
            AppendDescriptor(builder, FormatTypeExpression(serviceType), implementationType, registration.Lifetime, registration.KeyExpression);
        }
    }

    private static void AppendDescriptor(StringBuilder builder, string serviceType, string implementationType, RegistrationLifetime lifetime, string? keyExpression)
    {
        builder.Append("        services.Add(new ServiceDescriptor(");
        builder.Append(serviceType);
        builder.Append(", ");

        if (keyExpression is not null)
        {
            builder.Append(keyExpression);
            builder.Append(", ");
        }

        builder.Append(implementationType);
        builder.Append(", ServiceLifetime.");
        builder.Append(lifetime);
        builder.AppendLine("));");
    }

    private static string FormatTypeExpression(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is INamedTypeSymbol namedTypeSymbol && namedTypeSymbol.IsGenericType && namedTypeSymbol.TypeArguments.Any(argument => argument.TypeKind == TypeKind.TypeParameter))
        {
            typeSymbol = namedTypeSymbol.ConstructUnboundGenericType();
        }

        return $"typeof({typeSymbol.ToDisplayString(FullyQualifiedTypeFormat)})";
    }

    private static bool TryReadLifetime(AttributeData attribute, out RegistrationLifetime lifetime, out string? keyExpression, out List<ITypeSymbol> serviceTypes)
    {
        serviceTypes = new List<ITypeSymbol>();
        keyExpression = null;

        if (attribute.AttributeClass is not INamedTypeSymbol attributeClass)
        {
            lifetime = default;
            return false;
        }

        if (IsFamily(attributeClass, "SingletonAttribute"))
        {
            lifetime = RegistrationLifetime.Singleton;
            ReadKeyAndServices(attribute, attributeClass, serviceTypes, ref keyExpression);
            return true;
        }

        if (IsFamily(attributeClass, "ScopedAttribute"))
        {
            lifetime = RegistrationLifetime.Scoped;
            ReadKeyAndServices(attribute, attributeClass, serviceTypes, ref keyExpression);
            return true;
        }

        if (IsFamily(attributeClass, "TransientAttribute"))
        {
            lifetime = RegistrationLifetime.Transient;
            ReadKeyAndServices(attribute, attributeClass, serviceTypes, ref keyExpression);
            return true;
        }

        if (!IsFamily(attributeClass, "LifetimeAttribute"))
        {
            lifetime = default;
            return false;
        }

        if (attribute.ConstructorArguments.Length == 0)
        {
            lifetime = default;
            return false;
        }

        if (attribute.ConstructorArguments[0].Type?.Name == "ServiceLifetime")
        {
            lifetime = (RegistrationLifetime)Convert.ToInt32(attribute.ConstructorArguments[0].Value!);
            ReadServicesFromLifetimeAttribute(attribute, attributeClass, serviceTypes, 1);
            return true;
        }

        if (attribute.ConstructorArguments.Length > 1 && attribute.ConstructorArguments[1].Type?.Name == "ServiceLifetime")
        {
            keyExpression = FormatTypedConstant(attribute.ConstructorArguments[0]);
            lifetime = (RegistrationLifetime)Convert.ToInt32(attribute.ConstructorArguments[1].Value!);
            ReadServicesFromLifetimeAttribute(attribute, attributeClass, serviceTypes, 2);
            return true;
        }

        lifetime = default;
        return false;
    }

    private static void ReadKeyAndServices(AttributeData attribute, INamedTypeSymbol attributeClass, List<ITypeSymbol> serviceTypes, ref string? keyExpression)
    {
        if (attributeClass.TypeArguments.Length > 0)
        {
            serviceTypes.AddRange(attributeClass.TypeArguments);
        }

        if (attribute.ConstructorArguments.Length == 1 && attribute.ConstructorArguments[0].Kind != TypedConstantKind.Array)
        {
            keyExpression = FormatTypedConstant(attribute.ConstructorArguments[0]);
            return;
        }

        foreach (var argument in attribute.ConstructorArguments)
        {
            if (argument.Kind == TypedConstantKind.Array)
            {
                foreach (var value in argument.Values)
                {
                    if (value.Value is ITypeSymbol typeSymbol)
                    {
                        serviceTypes.Add(typeSymbol);
                    }
                }

                continue;
            }

            if (keyExpression is null && argument.Type?.Name != "ServiceLifetime")
            {
                keyExpression = FormatTypedConstant(argument);
            }
        }
    }

    private static void ReadServicesFromLifetimeAttribute(AttributeData attribute, INamedTypeSymbol attributeClass, List<ITypeSymbol> serviceTypes, int startIndex)
    {
        if (attributeClass.TypeArguments.Length > 0)
        {
            serviceTypes.AddRange(attributeClass.TypeArguments);
        }

        for (var index = startIndex; index < attribute.ConstructorArguments.Length; index++)
        {
            var argument = attribute.ConstructorArguments[index];
            if (argument.Kind != TypedConstantKind.Array)
            {
                continue;
            }

            foreach (var value in argument.Values)
            {
                if (value.Value is ITypeSymbol typeSymbol)
                {
                    serviceTypes.Add(typeSymbol);
                }
            }
        }
    }

    private static string FormatTypedConstant(TypedConstant constant)
    {
        if (constant.Value is null)
        {
            return "null";
        }

        return constant.Kind switch
        {
            TypedConstantKind.Array => "new object?[] { " + string.Join(", ", constant.Values.Select(FormatTypedConstant)) + " }",
            TypedConstantKind.Type when constant.Value is ITypeSymbol typeSymbol => FormatTypeExpression(typeSymbol),
            TypedConstantKind.Enum => $"({constant.Type?.ToDisplayString(FullyQualifiedTypeFormat)}){constant.Value}",
            TypedConstantKind.Primitive when constant.Value is string stringValue => ToLiteral(stringValue),
            TypedConstantKind.Primitive when constant.Value is char charValue => ToLiteral(charValue),
            TypedConstantKind.Primitive => Convert.ToString(constant.Value, System.Globalization.CultureInfo.InvariantCulture) ?? "null",
            _ => constant.Value.ToString() ?? "null"
        };
    }

    private static string ToLiteral(string value)
    {
        return "\"" + value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n") + "\"";
    }

    private static string ToLiteral(char value)
    {
        return value switch
        {
            '\\' => "'\\\\'",
            '\'' => "'\\\''",
            '\r' => "'\\r'",
            '\n' => "'\\n'",
            '\t' => "'\\t'",
            _ => $"'{value}'"
        };
    }

    private static bool CanRegisterAsService(INamedTypeSymbol implementationType, ITypeSymbol serviceType)
    {
        if (serviceType is INamedTypeSymbol namedServiceType && namedServiceType.IsGenericType && namedServiceType.TypeArguments.Any(argument => argument.TypeKind == TypeKind.TypeParameter))
        {
            serviceType = namedServiceType.ConstructUnboundGenericType();
        }

        if (serviceType is INamedTypeSymbol genericServiceType && genericServiceType.IsUnboundGenericType)
        {
            return GetCandidateServiceTypes(implementationType)
                .OfType<INamedTypeSymbol>()
                .Any(candidate => candidate.IsGenericType && SymbolEqualityComparer.Default.Equals(candidate.OriginalDefinition, genericServiceType.OriginalDefinition));
        }

        return GetCandidateServiceTypes(implementationType)
            .Any(candidate => SymbolEqualityComparer.Default.Equals(candidate, serviceType));
    }

    private static IEnumerable<ITypeSymbol> GetCandidateServiceTypes(INamedTypeSymbol implementationType)
    {
        yield return implementationType;

        foreach (var interfaceType in implementationType.AllInterfaces)
        {
            yield return interfaceType;
        }

        var current = implementationType.BaseType;
        while (current is not null)
        {
            yield return current;
            current = current.BaseType;
        }
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
    {
        var current = symbol;
        while (current is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, baseType.OriginalDefinition))
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private static bool IsFamily(INamedTypeSymbol symbol, string familyName)
    {
        var current = symbol;
        while (current is not null)
        {
            if (current.Name == familyName)
            {
                return true;
            }

            current = current.BaseType;
        }

        return false;
    }

    private sealed class RegistrationBuilder
    {
        private readonly HashSet<ITypeSymbol> serviceTypes = new(SymbolEqualityComparer.Default);

        public RegistrationBuilder(RegistrationLifetime lifetime, string? keyExpression)
        {
            Lifetime = lifetime;
            KeyExpression = keyExpression;
        }

        public RegistrationLifetime Lifetime { get; }

        public string? KeyExpression { get; }

        public void AddServiceType(ITypeSymbol serviceType)
        {
            serviceTypes.Add(serviceType);
        }

        public Registration Build(INamedTypeSymbol implementationType)
        {
            var orderedServiceTypes = serviceTypes
                .OrderBy(serviceType => serviceType.ToDisplayString(FullyQualifiedTypeFormat), StringComparer.Ordinal)
                .ToArray();

            return new Registration(implementationType, orderedServiceTypes, Lifetime, KeyExpression);
        }
    }

    private sealed record Registration(INamedTypeSymbol ImplementationType, ITypeSymbol[] ServiceTypes, RegistrationLifetime Lifetime, string? KeyExpression);

    private readonly record struct RegistrationKey(RegistrationLifetime Lifetime, string? KeyExpression);

    private sealed class RegistrationKeyComparer : IEqualityComparer<RegistrationKey>
    {
        public static RegistrationKeyComparer Instance { get; } = new();

        public bool Equals(RegistrationKey x, RegistrationKey y)
        {
            return x.Lifetime == y.Lifetime && StringComparer.Ordinal.Equals(x.KeyExpression, y.KeyExpression);
        }

        public int GetHashCode(RegistrationKey obj)
        {
            unchecked
            {
                var hash = (int)obj.Lifetime;
                hash = (hash * 397) ^ StringComparer.Ordinal.GetHashCode(obj.KeyExpression ?? string.Empty);
                return hash;
            }
        }
    }

    private enum RegistrationLifetime
    {
        Singleton = 0,
        Scoped = 1,
        Transient = 2,
    }
}
